#!/bin/ksh
#PBS -l select=1:ncpus=32:mpiprocs=32
#PBS -N Ag/10/4
#PBS -l walltime=10:00:00
#PBS -q standard
#PBS -l application=vasp
#PBS -A ONRDC40463482
#PBS -j oe

cd $PBS_O_WORKDIR
#export VASP=/usr/local/applic/vasp/5.3.5/bin/vasp

aprun -n 32 /usr/local/applic/vasp/5.3.5/bin/vasp_real 
